name: Flask Migrations and Seeds Workflow
description: Automatically sets up Python, installs dependencies, and runs Flask migrations and seeds on a PostgreSQL database.

# This is what triggers the action
on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]
    branches: ['main']

jobs:
  build-and-test-migrations-and-seeds:
    runs-on: ubuntu-latest

    services:
      postgres:
        # https://hub.docker.com/_/postgres
        # you could pin a specific version here
        image: postgres
        env:
        # these could be moved to secrets, but they're dummy values
        # probably best to use secrets in your actual project
        # google "github secrets" for more info
          POSTGRES_PASSWORD: password
          POSTGRES_USER: username
          POSTGRES_DB: dbname
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
      # this is Render's default version of python
      # https://render.com/docs/python-version#:~:text=Python%20version%203.11.,Python%20version%20(e.g.%2C%203.9.
        python-version: '3.11'

    # Cache Python dependencies
    # https://github.com/actions/cache/blob/main/caching-strategies.md
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # Install dependencies
    # read pip docs for more info on --no-cache-dir
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install --no-cache-dir psycopg2


    - name: Run migrations and seed database

      # these could be moved to secrets, but they're dummy values anyway
      # probably best to use secrets in a real project
      # google "github secrets" for more info
      env:
        FLASK_APP: ${{ secrets.FLASK_APP }}
        SCHEMA: ${{ secrets.SCHEMA }}
        FLASK_ENV: ${{ secrets.FLASK_ENV }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        flask db upgrade
        flask seed all

